import Head from "next/head";

import ErrorLayout from "../templates/errorLayout";
import ErrorSection from "../components/sections/ErrorSection";

const Custom500 = () => {
  return (
    <>
      <Head>
        <title>[STU] - Server Error</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ErrorLayout>
        <ErrorSection code="500" message="Server Error" />
      </ErrorLayout>
    </>
  );
};

export default Custom500;
